config/routes.rb
Rails.application.routes.draw do
  resources :projects do
    resources :tasks
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
class Project < ApplicationRecord
    has_many :tasks, dependent: :destroy
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    before_action :set_project, only: [:show, :edit, :update, :destroy]
  
    def index
      @projects = Project.all
      if @projects.empty?
        flash.now[:notice] = 'No projects found. You can create a new project below.'
      end
    end
  
    def show
    end
  
    def new
      @project = Project.new
    end
  
    def edit
    end
  
    def create
      @project = Project.new(project_params)
  
      if @project.save
        redirect_to @project, notice: 'Project was successfully created.'
      else
        render :new
      end
    end
  
    def update
      if @project.update(project_params)
        redirect_to @project, notice: 'Project was successfully updated.'
      else
        render :edit
      end
    end
  
    def destroy
        @project = Project.find(params[:id])
        @project.destroy
        redirect_to projects_path, notice: 'Project was successfully destroyed.'
    end
    
               
  
    private
  
    def set_project
      @project = Project.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to projects_path, alert: 'Project not found.'
    end
  
    def project_params
      params.require(:project).permit(:name, :description)
    end
  end
  

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :set_project
    before_action :set_task, only: [:show, :edit, :update, :destroy]
  
    def index
      @tasks = @project.tasks
    end
  
    def show
    end
  
    def new
      @task = @project.tasks.build
    end
  
    def edit
    end
  
    def create
      @task = @project.tasks.build(task_params)
  
      if @task.save
        redirect_to project_tasks_path(@project), notice: 'Task was successfully created.'
      else
        render :new
      end
    end
  
    def update
      if @task.update(task_params)
        redirect_to project_tasks_path(@project), notice: 'Task was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
        @task = @project.tasks.find(params[:id])
        @task.destroy
        redirect_to project_tasks_path(@project), notice: 'Task was successfully destroyed.'
    end
      

    private
  
    def set_project
      @project = Project.find(params[:project_id])
    end
  
    def set_task
      @task = @project.tasks.find(params[:id])
    end
  
    def task_params
      params.require(:task).permit(:name, :description, :due_date)
    end
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true, html: { class: 'form' }) do |form| %>
    <% if project.errors.any? %>
      <div id="error_explanation" class="error">
        <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>
        <ul>
          <% project.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name, class: 'text-input' %>
    </div>
  
    <div class="field">
      <%= form.label :description %>
      <%= form.text_area :description, class: 'text-area' %>
    </div>
  
    <div class="actions">
      <%= form.submit 'Save', class: 'btn btn-primary' %>
    </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Edit Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1> Major Projects</h1>

<% if @projects.empty? %>
  <p>No projects found. You can create a new project below.</p>
<% else %>
<table class="table">
<thead>
  <tr>
    <th>Name of project</th>
    <th>Description of the project</th>
    <th colspan="3"></th>
  </tr>
</thead>

<tbody>
  <% @projects.each do |project| %>
    <tr>
      <td><%= project.name %></td>
      <td><%= project.description %></td>
      <td><%= link_to 'Show', project, class: 'btn btn-primary' %></td>
      <td><%= link_to 'Edit', edit_project_path(project), class: 'btn btn-secondary' %></td>
      <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
    </tr>
  <% end %>
</tbody>
</table>

<% end %>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>


<h2>Tasks</h2>
<% if @project.tasks.empty? %>
  <p class 'btn-primary'>No tasks yet. <%= link_to 'Add a Task', new_project_task_path(@project) %></p>
<% else %>
  <ul>
    <% @project.tasks.each do |task| %>
      <li><%= task.name %></li>
    <% end %>
  </ul>
  <%= link_to 'Add a Task', new_project_task_path(@project) %>
<% end %>

app/views/tasks/_form.html.erb
<%= form_with(model: [@project, @task], local: true, class: 'task-form') do |form| %>
    <% if @task.errors.any? %>
      <div id="error_explanation" class="error">
        <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>
        <ul>
          <% @task.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name, class: 'text-input' %>
    </div>
  
    <div class="field">
      <%= form.label :description %>
      <%= form.text_area :description, class: 'text-area' %>
    </div>
  
    <div class="field">
      <%= form.label :due_date %>
      <%= form.date_field :due_date, class: 'date-input' %>
    </div>
  
    <div class="actions">
      <%= form.submit 'Save', class: 'btn btn-primary' %>
    </div>
  <% end %>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>
<%= render 'form', task: @task %>
<%= link_to 'Back', project_tasks_path(@project) %>

app/views/tasks/index.html.erb
<h1>Tasks</h1>

<% if @tasks.empty? %>
  <p>No tasks found for this project. You can create a new task below.</p>
<% else %>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Due Date</th>
        <th colspan="3"></th>
      </tr>
    </thead>
  
    <tbody>
      <% @tasks.each do |task| %>
        <tr>
            <td><%= task.name %></td>
            <td><%= task.description %></td>
            <td><%= task.due_date %></td>
            <td><%= link_to 'Show', project_task_path(@project, task) %></td>
            <td><%= link_to 'Edit', edit_project_task_path(@project, task) %></td>
            <td><%= link_to 'Destroy', project_task_path(@project, task), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
        <% end %>
    </tbody>
  </table>
<% end %>

<br>

<%= link_to 'New Task', new_project_task_path(@project) %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', project_tasks_path(@project) %>

app/views/tasks/show.html.erb
<h1 class="task-name"><%= @task.name %></h1>
<p class="task-description"><strong>Description:</strong> <%= @task.description %></p>
<p class="task-due-date"><strong>Due Date:</strong> <%= @task.due_date %></p>
<%= link_to 'Back', project_tasks_path(@project), class: "btn btn-back" %>